version: "3.9"
services:
  db:
    image: postgres:13.2-alpine
    restart: always
    environment:
      TZ: 'GMT+2'
      PGTZ: 'GMT+2'
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT_HOST}:${POSTGRES_PORT}"
    volumes:
      - "${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d"
      - "${POSTGRES_PGDATA}:/var/lib/postgresql/data"
