version: "3.9"
services:
  db:
    container_name: PostgresDB
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT_HOST}:${POSTGRES_PORT}"
    volumes:
      - "${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d"
      - "${POSTGRES_PGDATA}:/var/lib/postgresql/data"
  server:
    container_name: GinServer
    image: kenfront/gin-todolist
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: always
    depends_on:
        - db
