version: "3.9"
services:
  db:
    container_name: Postgres
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "${POSTGRES_PGDATA}:/var/lib/postgresql/data"
  migrate:
    container_name: MigratePostgres
    image: migrate/migrate:v4.14.1
    restart: on-failure
    command: >-
      -source=file://migrations
      -database=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSLMODE}
      goto
      ${POSTGRES_VERSION}
    volumes:
      - "${POSTGRES_MIGRATION_FILES_PATH}:/migrations"
    depends_on:
      - db
  server:
    container_name: Gin
    image: "${SERVER_IMAGE}:${SERVER_IMAGE_VERSION}"
    restart: always
    depends_on:
      - db
  web:
    container_name: Nextjs
    image: "${WEB_IMAGE}:${WEB_IMAGE_VERSION}"
    restart: always
    environment:
      DOMAIN: Gin
  proxy:
    container_name: Nginx
    image: nginx:1.21-alpine
    restart: always
    ports:
      - 80:80
    environment:
      NGINX_HOST: ${DOMAIN}
    volumes:
      - "./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template"
    depends_on:
      - web
      - server
