stateDiagram-v2
    state Gin {
        [*] --> GlobalMiddleware
        GlobalMiddleware --> PrivateMiddleware
        GlobalMiddleware --> SignIn
        GlobalMiddleware --> SignOut
        GlobalMiddleware --> AddUser
        ControllerTodos --> Todos
        ControllerUsers --> Users
        SignIn --> Users
        AddUser --> Users
        SignOut
        state GlobalMiddleware {
            CustomLogger --> Logger
            Logger --> ErrorHandler
        }
        state PrivateMiddleware {
            AuthGuard --> ControllerTodos
            AuthGuard --> ControllerUsers
        }
        state ControllerUsers {
            DeleteUser
            GetUser
            PatchUser
        }
        state ControllerTodos {
            AddTodo
            DeleteTodoById
            GetTodoById
            GetTodoList
            PatchTodoById
        }
    }
    state Migrate {
        [*] --> Users
        [*] --> Todos
    }
    state Postgres {
        Users --> Todos
    }