name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache go module
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-v3-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3

      - name: Test
        run: make testAll

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux go build -o ./app ./src/main.go
